/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/


#include <iostream>

int main()
{
    int sum=2,a=1,b=2,c=0;
    for(int i=0;c<4000000;i++){
        c=a+b;
        a=b;
        b=c;
        if(c%2==0){
            sum+=c;
        }
    }
    std::cout << sum << std::endl;
    return 0;
}
//Answer:4613732
